# Green AI: The Environmental Footprint

## Impact of AI on Environment {-}

In the field of sustainable development, AI is often touted as the end-all solution to optimization. AI does offer a lot of sustainability solutions, but it doesn't come without its drawbacks. AI consumes a lot of resources to train its models. Water is consumed to cool the computers, energy is consumed to power the computers, and then the old hardware is thrown away. While AI offers a lot of promising advancements, being conscious of the negative effects is important to mitigating damage caused by AI

## Water Usage {-}

One way in which AI can negatively affect the environment is through the massive amounts of water it consumes. Through energy generation for AI, training AI, and transmitting the data needed for AI, AI can consume a lot of water. It is estimated that training GPT3, the Large Language Model used by Chat-GPT, used 700,000 liters of clean fresh water [@Guerrini_2023]. Training AI also uses large amounts of electricity, and with our current generation mix, most electricity generation also consumes water. In most of the United States, this isn't an issue, but most tech companies are located in the western United States, which is hit particularly hard by water scarcity and stress. As seen in the map below, published by the U.S. Global Change Research Program, water stress is almost entirely concentrated in the West. Water scarcity is a growing issue, it is estimated by the United Nations International Children's Emergency Fund [@UNWater_2023] that as early as 2025 half of the world's population could experience some form of water scarcity.


AI will have some positive impacts on water use. Allowing more precise water use in agriculture and efficient resource allocation in residential areas will help offset some of the negative impacts. As AI grows more prominent and more data is needed to train models its water use will grow exponentially but there are some methods we can use to reduce its negative impacts. By making conscious effects to minimize the water use of AI training and Data transfer, the impact can be significantly reduced. According to Forbes, Amazon, Meta, Google, and Microsoft, have pledged to become "water positive" by 2030 [@Guerrini_2023].


## Energy Consumption {-}


As well as consuming water, AI consumes a lot of energy. Storing data, transferring data, and training models with that data are all energy-intensive tasks. As AI advances it will use more and more data and consume more and more energy. For example, in a report by Wired, they estimated that a recent Open AI model focused on solving Rubik's cubes used 2.8 gigawatt-hours of energy to train which they equated to the same amount of power produced by three nuclear power plants in an hour [@Knight_2020]. While there was some doubt about the exact energy usage, all of the AI models like Chat-GPT or Dalle- 2 and most other widely used models likely consumed similar amounts of energy. In the United States, the energy generation mix is largely fossil fuels, with only 12% of energy being renewable [@Guerrini_2023]. This means increasing energy use is directly responsible for increased greenhouse gas emissions. While AI training can be made by some estimates up to 75% more efficient by some estimates, it is important to consider the energy use of AI and its effect on climate change [@Champion_2023].


## Electronic Waste {-}

Another problem that comes with the increasing popularity of AI is electronic waste. E-waste is all the computing parts that are thrown away due to being broken, out of date, or obsolete. While the problem hasn't hit AI extremely hard, a good model of what might happen is the e-waste associated with cryptocurrencies. It is currently estimated that Bitcoin “currently cycles through 30.7 metric kilotons of equipment per year” [@Hern_2021]. This amount of waste stacks up quickly. By bringing attention to this problem, it is possible to practice more sustainable AI development.


## Electronic Waste {-}

Another problem that comes with the increasing popularity of AI is electronic waste. E-waste is all the computing parts that are thrown away due to being broken, out of date, or obsolete. While the problem hasn't hit AI extremely hard, a good model of what might happen is e-waste associated with crypto currencies. It is currently estimated that bitcoin “currently cycles through 30.7 metric kilotons of equipment per year” [@Hern_2021]. This amount of waste stacks up quickly. By bringing attention to this problem, it is possible to practice more sustainable AI development.