# The Digital Divide and AI Accessibility

This page seeks to inform the reader about the societal impacts of AI, specifically looking at how populations may grow to be increasingly separate as technology impacts play out. 

## Introducing the Digital Divide {-}

By definition, the digital divide is the gap between those with Internet access and those without it [@CharlieMuller_2022]. This term was coined in the mid-1990s, and as new technologies such as AI continue to emerge and develop, the digital divide only grows in new ways. Access to these technologies has come increasingly critical to a country or region’s economic, political, and social success. The digital divide seeks to explain that not everyone has access to the same technological resources, as this access fluctuates depending on various factors such as education, income, or race [@Taylor_2023]. Although various demographic or social factors can impact this divide, it’s also worth mentioning the two other substages of the digital divide that were first described by Jakon Nielson in 2006 [@Nielsen_2006]. 

### The Types of Divides {-}

* Nielsen believes the digital divide as it is normally used is synonymous with the <span style="text-decoration: underline;">economic divide</span> as it is often focused on the affordability of the technology. 
* The <span style="text-decoration: underline;">usability divide</span> explains that many populations would not know what to do with a computer, even if they had free access to one. In the past, the groups most at risk here were the elderly and those with low literacy. 
* The <span style="text-decoration: underline;">empowerment divide</span> considers how we use technology to empower ourselves. This divide explains that humans need to be more aware of all of the technological capabilities computer systems actually have and feel comfortable using them. 

Given this information, the rapid emergence of Artificial Intelligence is likely to mimic the dispersion that occurred with the Internet and other emerging technologies. At this point, it is not possible to predict how AI will disperse and/or stick with populations, yet it is important to look at the current information we have about the world. As of April 2023, 64.6% of the global population makes up 5.18B internet users worldwide [@AniPetrosyan_22_2023]. In high-income countries, Internet usage is about 90% while it sits just above 25% for low-income countries. The graph below also shows the number of worldwide internet users over time. 

image needed


## AI and the Digital Divide {-}

Although the digital divide has commonly been used to talk about the gap in internet access between populations, AI will likely have its own type of divide emerge rather soon. To be more specific, we are more likely to see populations that have a strong understanding of what AI is and how it can be used, use it more often. These groups will likely be able to afford it and will be able to access it as much as they want, especially because they’ll find the information valuable. On the flip side, many populations will remain uneducated about what AI is, which could be because of a variety of reasons. If an individual or group doesn’t have access to the internet, AI is irrelevant. At the same time, if they don’t have the infrastructure in place for AI to be useful, it’s unlikely to be adopted. Various barriers could limit AI’s impact in different spaces. 

In order to assess how much of a social disruption AI can be globally in terms of this potential socio-economic divide, it’s important to look at what countries are using AI the most right now. This current list is (higher percent usage listed first): United States, India, Canada, Germany, United Kingdom, Spain, Brazil, Mexico, Australia, Italy, France, and Japan [@Watters_2023a]. Out of this list of twelve countries, only three of them are developing which are India, Brazil, and Mexico [@Team_2023]. This alone shows that AI is impacting the areas of the world that are already deemed as further developed, typically economically and/or technologically as those can go hand in hand. 

The United States, the country with the highest percentage of AI use in the world, still has a large portion of the population that is not fully aware of what AI actually is and what it can do beyond very simple capabilities. Even though this is the case, it’s interesting to look at how a strong understanding of AI doesn’t necessarily equate to trust in AI companies. Perception can vastly change depending on where an individual is from, which is shown in the chart below. Countries more open to AI may be quicker to adopt and those that aren’t may be slower. That slow adoption could be costly in the short or long term. 

image needed

These insights are helpful to think about, but at this point, it’s critical to further dive into AI’s current costs and accessibility. 

## Costs of AI - Economic Divide  {-}

For any business offering AI, the costs are incredibly high to both develop the product and maintain it. The cost ultimately depends on what the AI is intended to be used for, as larger business solutions tend to be more expensive than smaller use cases like ChatGPT’s chatbot by OpenAI. Earlier we described the economic divide, and the cost of AI falls right into this general bucket. Populations that are better off economically are in a better position to start utilizing AI tools, which in turn could make them even more productive or profitable than before. This will likely increase the gap between populations thriving financially and those simply getting by, as their global competitors will have resources they won’t be able to get their hands on. 

If we were to focus on what simple AI tools cost to an individual user, we’d look at what we’re seeing offered today. For example, Chat GPT is something every single university and school is talking about. Chat GPT is estimated to cost around \$700,000 per day to OpenAI, in order to keep the tool running efficiently [@Agomuoh_2023]. Even though the costs are this high, the basic version of ChatGPT is free, while the paid version is \$20/month. With resources like this that have lower user costs, accessibility between populations thankfully becomes less of a concern. However this is the case, the language with which the data has been trained becomes a larger issue. 

## AI’s Changing Usefulness  {-}

In the United States, AI’s impact has been large. Within a short span of time, individuals and businesses have been looking for ways to integrate AI into their lives strategically. This is because the vast amount of information and tasks that AI resources can contribute are relevant. By relevant, we mean that the information that the AI software was trained on is in the English language, a lot of it from an American perspective too. 

Given this, it’s important to consider how having AI trained in the English language could create global silos or further create divides in our society. Many may assume that English is spoken around the globe, but recent statistics show that 75% of the world’s population doesn’t speak English at all [@Authors_2023]. This fact means that 1 out of 4 people on the planet speak English. If most of the AI tools out there today are trained on data pertaining to English-speaking individuals, that means the majority of people will find these tools useless to at least some degree. Some AI tools may be language agnostic if it involves physically doing something, but AI used to mimic human thinking or ideation can be very off course if it wasn’t trained in the same culture or language. Direct translations aren’t always enough to make something connect with a different audience.


## Looking Forward  {-}

It is easy to think of AI in silos, but if one is to anticipate how AI will change the world, these factors need to be considered. The large differences between cultures and regions will definitely impact AI’s spread and the openness to which it is adopted. But even as it is adopted, will AI hold the same value for a company in the US versus Europe versus Africa? Will areas with less exposure to new technology even understand how AI could change the way they go about life? Even if they understand the impacts, would they know how to use AI properly? If demand keeps increasing, who will be able to afford it and who will get pushed out? These are questions that need to be considered as AI begins to grow.


